import{a as f,S as h,i as l}from"./assets/vendor-0Fq3u7cb.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const i of s.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&n(i)}).observe(document,{childList:!0,subtree:!0});function o(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function n(e){if(e.ep)return;e.ep=!0;const s=o(e);fetch(e.href,s)}})();const b="45127620-5b07992107ac4e8771e67df86",$="https://pixabay.com/api",L=15;async function u(t,r){const o=`${$}/?key=${b}&q=${encodeURIComponent(t)}&image_type=photo&orientation=horizontal&safesearch=true&per_page=${L}&page=${r}`;try{return(await f.get(o)).data}catch(n){throw new Error(`HTTP error! status: ${n.response.status}`)}}const w=document.querySelector(".gallery");function g(t){const r=t.map(o=>P(o)).join("");w.insertAdjacentHTML("beforeend",r)}function P({webformatURL:t,largeImageURL:r,tags:o,likes:n,views:e,comments:s,downloads:i}){return`
    <a class="gallery__item" href="${r}">
      <div class="photo-card">
        <img src="${t}" alt="${o}" loading="lazy" />
        <div class="info">
          <p class="info-item"><b>Likes:</b> ${n}</p>
          <p class="info-item"><b>Views:</b> ${e}</p>
          <p class="info-item"><b>Comments:</b> ${s}</p>
          <p class="info-item"><b>Downloads:</b> ${i}</p>
        </div>
      </div>
    </a>
  `}const E=document.querySelector("#search-form"),I=document.querySelector(".gallery"),a=document.querySelector(".loading-indicator"),d=document.querySelector("#load-more-button");let p=new h(".gallery a"),c=1,y="";const m=15;E.addEventListener("submit",S);d.addEventListener("click",v);async function S(t){t.preventDefault();const r=t.target.elements.searchQuery.value.trim();if(r===""){l.warning({title:"Warning",message:"Please enter a search term!",position:"topRight"});return}y=r,c=1,I.innerHTML="",a.style.display="block",d.style.display="none";try{const o=await u(r,c);if(a.style.display="none",o.hits.length===0){l.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}g(o.hits),p.refresh(),o.totalHits>m&&(d.style.display="block")}catch(o){a.style.display="none",l.error({title:"Error",message:"Failed to fetch images. Please try again later!",position:"topRight"}),console.error("Error in fetching images:",o)}}async function v(){c+=1,a.style.display="block";try{const t=await u(y,c);a.style.display="none",g(t.hits),p.refresh(),c*m>=t.totalHits?(d.style.display="none",l.info({title:"Info",message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):q()}catch(t){a.style.display="none",l.error({title:"Error",message:"Failed to fetch images. Please try again later!",position:"topRight"}),console.error("Error in fetching images:",t)}}function q(){const{height:t}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})}
//# sourceMappingURL=commonHelpers.js.map
